### ISSUE TITLE
genetski algoritem

### ISSUE THREAD

**Issue by jakamun** [ZavbiA/Graffiti-conjecture-on-Randic-index-vs.-radius#1]
V datoteki genetic_algorithm.ipynb sva napisala genetski algoritem s katerim poskušava ovreči najino tezo, vendar nama to ne uspe. Zanima naju, če je kje v kodi napaka, ali samo slabe argumente izbirava?

**Comment by jaanos** [comment]
Opozoril bi na to: ko naredita
```sage
kopija = graf
```
se ne naredi kopija, pač pa je `kopija` zdaj samo drugo ime za `graf`. Drugače povedano, spremembe na grafu `kopija` se poznajo tudi na grafu `graf`. Če želita narediti kopijo, naredita
```sage
kopija = Graph(graf)
```

Drugače pa seveda ni nujno, da protiprimer domnevi dejansko obstaja - tj., domneva je morda pravilna. Poskusita svoj program pognati s čim večjim številom parametrov in o tem poročajta v poročilu (ob tem merita čase izvajanja). Super bi bilo, če najdeta protiprimer, če ga pa ne, pa seveda tudi ni nič narobe.
